# Generated by Django 3.1.7 on 2021-04-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='leave_balance',
            field=models.IntegerField(default=30),
        ),
    ]
