# Generated by Django 3.1.7 on 2021-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210403_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='leave_balance_old',
            field=models.IntegerField(default=0),
        ),
    ]
