# Generated by Django 3.1.7 on 2021-04-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_staff_leave_balance_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='leave_balance_old',
        ),
    ]
