# Generated by Django 3.1.7 on 2021-04-02 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(help_text='leave start date is on ..', null=True)),
                ('enddate', models.DateField(help_text='coming back on ...', null=True)),
                ('resumptiondate', models.DateField(help_text='coming back on ...', null=True)),
                ('leavetype', models.CharField(blank=True, choices=[('SICK', 'Sick leave'), ('EXAM', 'Exam leave'), ('ANNUAL', 'Annual leave'), ('COMPASSIONATE', 'Compassionate leave')], default='SICK', max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('rejected', 'rejected')], default='PENDING', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
