# Generated by Django 3.1.7 on 2021-04-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_auto_20210403_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_balance_old',
            field=models.IntegerField(default=0),
        ),
    ]
