# Generated by Django 3.1.7 on 2021-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0005_auto_20210403_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='final_balance_old',
            new_name='final_balance',
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_approved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
